export default {
    "subtitle": "How joining Panot to animate remotely on Framestore's systems became a masterclass in quadruped weight and realistic timing.",
    "experienceTitle": "Surviving Impostor Syndrome and Quadruped Weight",
    "content": [
        "Joining Panot was absolute pure luck. On a Friday, I finished up my previous project in Berlin, packed my entire life into a couple of bags, and by Monday morning, I was sitting in the Barcelona studio, not knowing a single soul. It was a complete whirlwind. When I walked in, I met the team and my supervisor, <a href=\"https://www.linkedin.com/in/ferran-casas-23b2292\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"underline font-bold hover:text-muted-foreground transition-colors\">Ferran Casas</a>, and immediately felt a massive wave of panic. Every single animator in that room had way more experience than me. They had all worked on huge, big-budget feature films before, and most of them already knew each other and had this amazing, established shorthand. Meanwhile, I was just trying to figure out where the coffee machine was and how to connect remotely to Framestore's massive, mind-bogglingly confusing pipeline.",
        "For the first month and a half, I was navigating a pretty solid dose of impostor syndrome, just trying to get my bearings among all these veterans. The ultimate test of patience was my very first shot in the movie... animating a character named <strong>WinterLamb</strong>. It was quite the struggle just to get that first shot approved.",
        "<div class=\"my-12 max-w-2xl mx-auto px-4 grid grid-cols-1 md:grid-cols-[auto_1fr] gap-8 md:gap-12 items-center\">\n  <!-- Image on the left (on top on vertical windows) -->\n  <div class=\"flex justify-center md:justify-start\">\n    <img src=\"/images/winterlamb.png\" alt=\"Screenshot from the movie The Sheep Detectives featuring WinterLamb\" class=\"w-full max-w-[240px] h-auto block select-none\" />\n  </div>\n  <!-- Quote on the right -->\n  <blockquote class=\"text-right not-italic\">\n    <span class=\"block text-2xl md:text-3xl font-black uppercase tracking-tight text-zinc-500 dark:text-zinc-400\">\"George loved me!\"</span>\n    <span class=\"block text-xl font-bold italic text-zinc-400 dark:text-zinc-500 mt-2\">- WinterLamb</span>\n  </blockquote>\n</div>",
        "Yes, that was the line. And honestly, the timing couldn't have been more perfect. While WinterLamb was crying out on my monitor about being loved, I was sitting there in my own little bubble of impostor syndrome, sweating through my shirt and half-convinced my next set of keyframes would get me sent back to Berlin. The contrast was hilarious in hindsight; this tiny, dramatic lamb crying for affection while I was staring at a massive, complex skeleton rig just hoping my animation curves made sense.",
        "But I got incredibly lucky. Meeting Ferran Casas was a lifesaver. He is easily one of the funniest, most practical, and genuinely kind supervisors I have ever met. No matter how much I struggled or how nervous I got, Ferran never gave up on me. He would pull up a chair, crack a joke to break my tension, and patiently show me how realistic quadruped weight shifts actually work.",
        "Slowly, through those sessions and the daily reviews with <a href=\"https://www.linkedin.com/in/hurtt/\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"underline font-bold hover:text-muted-foreground transition-colors\">Chris Hurtt</a>, I started to find my footing. Reviews from Chris became masterclasses in micro-details, teaching me how to transition from my stylized cartoon habits into ultra-realistic animal motion. I began to understand the confusing pipeline, the tools clicked, and my confidence grew alongside this wonderful crew of veterans."
    ]
};
